services:
  - type: web
    name: projectg-server
    env: docker
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 4000

  - type: web
    name: projectg-client
    env: docker
    dockerfilePath: ./client/Dockerfile
    dockerContext: ./client
    envVars:
      - key: VITE_API_URL
        sync: false
