-- Insert dummy stories (only if table is empty)
INSERT INTO stories (image, quote, name, role, location, year, "fullStory", "order")
SELECT * FROM (VALUES
  ('', 'Thanks to the scholarship, I am now able to study and dream of a better future.', 'Aarav Kumar', 'Scholarship Recipient', 'Imphal, Manipur', '2023', 'Aarav grew up in a small household where his parents worked as daily labourers. When the scholarship programme found him in Class 9, he was on the verge of dropping out. With the support he received, Aarav completed his Class 12 with distinction and is now pursuing a bachelor''s degree in computer science. He dreams of returning to his village and teaching coding to children who, like him, might otherwise have lost hope.', 0),
  ('', 'The support we received helped us rebuild our home and live with dignity again.', 'Sunita Devi', 'Community Beneficiary', 'Thoubal, Manipur', '2022', 'When a flood destroyed Sunita''s home in 2022, she had nothing left but hope. Project Generation''s disaster relief team reached her village within days, providing temporary shelter, food, and rebuilding support. Today, Sunita''s family lives in a stronger home and she has joined our community volunteer network to help others in times of crisis.', 1),
  ('', 'Volunteering here has been the most meaningful experience of my life.', 'Rohan Mehta', 'Volunteer', 'Bishnupur, Manipur', '2024', 'Rohan first joined Project Generation as a college student looking for meaningful ways to contribute. What started as weekend teaching sessions soon turned into a full commitment. He now leads a team of 20 volunteers coordinating health camps and education drives across three districts. "I came to give," he says, "but I received so much more in return."', 2),
  ('', 'Every contribution transformed not just my child''s future but our entire community.', 'Priya Sharma', 'Parent Beneficiary', 'Churachandpur, Manipur', '2023', 'Priya''s daughter, Deepa, was one of 60 children enrolled in our after-school learning programme. Before joining, Deepa could barely read. Within a year, she stood first in her class. Priya, moved by the transformation, began attending our parent awareness sessions and is now an advocate for girls'' education in her neighbourhood.', 3),
  ('', 'I never imagined clean water would change everything — it truly gave us a new life.', 'Meera Nair', 'Village Resident', 'Senapati, Manipur', '2021', 'For years, Meera''s village depended on a contaminated well that made children sick every monsoon. Project Generation''s water sanitation project installed a filtration system and educated families on hygiene practices. Waterborne illnesses in the village dropped by 80% in the following year. Meera says clean water did not just save lives — it gave the village back its dignity.', 4),
  ('', 'The skills training I received opened doors I never knew existed.', 'Samuel Osei', 'Vocational Graduate', 'Kangpokpi, Manipur', '2023', 'Samuel enrolled in our six-month electrician training programme with barely a Class 8 education and no income. By the end, he had passed the certification and secured his first contract. He now runs a small electrical services business employing two assistants from his community. "I used to wonder if someone like me could ever build something," he says. "Now I know I can."', 5),
  ('', 'Seeing my students read their first sentence was worth more than words can express.', 'Fatima Al-Hassan', 'Community Teacher', 'Ukhrul, Manipur', '2024', 'Fatima came to the literacy programme as a participant — a mother of three who had never been to school. After learning to read and write, she surprised everyone by asking to stay on as a teacher''s aide. Today she runs evening classes for women in her own lane, teaching reading, numeracy, and basic health literacy. She believes every woman who learns becomes a teacher herself.', 6),
  ('', 'From receiving help to leading others — that journey is something I cherish forever.', 'Diego Reyes', 'Farmer & Community Trainer', 'Pherzawl, Manipur', '2022', 'Diego was once a struggling farmer who had lost three consecutive harvests to poor soil management. After attending Project Generation''s agriculture training workshops, he learned about crop rotation and organic composting. His yield doubled in the first season. He then trained 30 other farmers in his area, and their collective income rose by an average of 40%. Diego now leads our agricultural mentorship circle.', 7)
) AS v(image, quote, name, role, location, year, "fullStory", "order")
WHERE NOT EXISTS (SELECT 1 FROM stories LIMIT 1);
