ALTER TABLE "whg_groups" ADD COLUMN IF NOT EXISTS "theme" TEXT NOT NULL DEFAULT '';
ALTER TABLE "whg_groups" ADD COLUMN IF NOT EXISTS "themeColor" TEXT NOT NULL DEFAULT '';

ALTER TABLE "lac_groups" ADD COLUMN IF NOT EXISTS "theme" TEXT NOT NULL DEFAULT '';
ALTER TABLE "lac_groups" ADD COLUMN IF NOT EXISTS "themeColor" TEXT NOT NULL DEFAULT '';

ALTER TABLE "hrds_groups" ADD COLUMN IF NOT EXISTS "theme" TEXT NOT NULL DEFAULT '';
ALTER TABLE "hrds_groups" ADD COLUMN IF NOT EXISTS "themeColor" TEXT NOT NULL DEFAULT '';

ALTER TABLE "cwg_groups" ADD COLUMN IF NOT EXISTS "theme" TEXT NOT NULL DEFAULT '';
ALTER TABLE "cwg_groups" ADD COLUMN IF NOT EXISTS "themeColor" TEXT NOT NULL DEFAULT '';

ALTER TABLE "fseds_groups" ADD COLUMN IF NOT EXISTS "theme" TEXT NOT NULL DEFAULT '';
ALTER TABLE "fseds_groups" ADD COLUMN IF NOT EXISTS "themeColor" TEXT NOT NULL DEFAULT '';
