ALTER TABLE "stories" ADD COLUMN IF NOT EXISTS "location" TEXT NOT NULL DEFAULT '';
ALTER TABLE "stories" ADD COLUMN IF NOT EXISTS "year" TEXT NOT NULL DEFAULT '';
ALTER TABLE "stories" ADD COLUMN IF NOT EXISTS "fullStory" TEXT NOT NULL DEFAULT '';
