ALTER TABLE "board_members" ADD COLUMN IF NOT EXISTS "image" TEXT NOT NULL DEFAULT '';
ALTER TABLE "board_members" ADD COLUMN IF NOT EXISTS "description" TEXT NOT NULL DEFAULT '';

ALTER TABLE "team_members" ADD COLUMN IF NOT EXISTS "image" TEXT NOT NULL DEFAULT '';
ALTER TABLE "team_members" ADD COLUMN IF NOT EXISTS "description" TEXT NOT NULL DEFAULT '';
