-- Extend impact-numbers section with editable stat card fields
UPDATE sections SET data = data || '{"stat0Value":"25,000+","stat0Label":"Lives Impacted","stat0Sub":"Across all programs","stat1Value":"10,000+","stat1Label":"Children Educated","stat1Sub":"Scholarships & school kits","stat2Value":"150+","stat2Label":"Communities Served","stat2Sub":"Urban, rural & tribal areas","stat3Value":"500+","stat3Label":"Active Volunteers","stat3Sub":"Giving time every month","stat4Value":"50,000+","stat4Label":"Meals Distributed","stat4Sub":"Through community kitchens","stat5Value":"12+","stat5Label":"Years of Service","stat5Sub":"Serving since 2013"}'::jsonb WHERE type = 'impact-numbers';

-- Extend impact-areas section with editable area card fields
UPDATE sections SET data = data || '{"area0Title":"Environment","area0Metric":"1,200+ beneficiaries","area0Description":"Community-led conservation, tree planting, and river clean-ups restore ecosystems and educate youth on sustainable living.","area1Title":"Education","area1Metric":"850+ students supported","area1Description":"Scholarships, school supplies, and mobile classrooms bring quality education to the most underserved children.","area2Title":"Health & Wellness","area2Metric":"2,300+ patients treated","area2Description":"Free health camps, vaccination drives, and maternal care programs reduce preventable illness across communities.","area3Title":"Hunger & Food","area3Metric":"640+ families fed","area3Description":"Community kitchens and food distribution networks deliver nutritious meals and build long-term food security.","area4Title":"Women Empowerment","area4Metric":"520+ women trained","area4Description":"Vocational training and micro-finance programs equip women with skills and capital to achieve financial independence.","area5Title":"Youth Development","area5Metric":"980+ youth engaged","area5Description":"Coding bootcamps, leadership workshops, and mentorship programs prepare young people for a competitive world."}'::jsonb WHERE type = 'impact-areas';

-- Extend impact-timeline section with editable milestone fields
UPDATE sections SET data = data || '{"milestone0Year":"2013","milestone0Title":"Project Generation Founded","milestone0Description":"A small group of students came together with a vision to serve their community through organized, sustained action.","milestone1Year":"2015","milestone1Title":"First 1,000 Lives Impacted","milestone1Description":"Our early programs in education and health reached the milestone of touching 1,000 lives across local communities.","milestone2Year":"2017","milestone2Title":"Five Societies Launched","milestone2Description":"Expanded reach by forming five specialized societies, each focusing on a distinct area of community development.","milestone3Year":"2019","milestone3Title":"10,000 Children Educated","milestone3Description":"Our education programs surpassed 10,000 children supported through scholarships, school kits, and mobile learning centers.","milestone4Year":"2021","milestone4Title":"500+ Active Volunteers","milestone4Description":"Our volunteer community grew to over 500 dedicated individuals contributing their time and skills every month.","milestone5Year":"2023","milestone5Title":"25,000+ Lives Impacted","milestone5Description":"Reached the landmark of 25,000 lives touched across 150+ communities — a testament to collective action."}'::jsonb WHERE type = 'impact-timeline';

-- Extend impact-testimonials section with editable testimonial fields
UPDATE sections SET data = data || '{"testimonial0Quote":"The scholarship I received from Project Generation changed everything. I was the first in my family to finish school. Now I want to give back the same way.","testimonial0Name":"Anita Sharma","testimonial0Location":"Rural District, UP","testimonial0Category":"Education","testimonial0Initials":"AS","testimonial1Quote":"The free health camp caught my husband''s illness early. Without Project Generation, we would never have afforded the tests. We are forever grateful.","testimonial1Name":"Rekha Devi","testimonial1Location":"Urban Slum, Bihar","testimonial1Category":"Health","testimonial1Initials":"RD","testimonial2Quote":"Their vocational training gave me the skills to start my own tailoring shop. Today I employ three other women from my village. That is real change.","testimonial2Name":"Sunita Kumari","testimonial2Location":"Semi-Urban, Rajasthan","testimonial2Category":"Empowerment","testimonial2Initials":"SK"}'::jsonb WHERE type = 'impact-testimonials';
